name: "Test Push with PAT"

on:
  workflow_dispatch:  # 手动触发

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Modify repo"
        run: |
          echo "Test push at $(date -u '+%Y-%m-%d %H:%M:%S')" >> test.txt

      - name: "Commit and push"
        run: |
          set -Eeuo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add test.txt
          git commit -m "Test push at $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/senshinya/singbox_ruleset.git HEAD:main
